---
title: "Estado Civil"
author: "Aguirre Alvarado Danna Paola"
output: html_document
date: "2025-09-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
nivel_educativo_ordenado <- factor(c("posdoctorado","preparatoria","preparatoria","doctorado","primaria",
                  "doctorado","preparatoria","secundaria","preparatoria","preparatoria",
                  "primaria","doctorado","secundaria","secundaria","secundaria",
                  "licenciatura","doctorado","primaria","maestria","posdoctorado",
                  "maestria","preparatoria","posdoctorado","doctorado","preparatoria",
                  "doctorado","maestria","primaria","licenciatura","secundaria",
                  "maestria","posdoctorado","doctorado","licenciatura","doctorado",
                  "posdoctorado","maestria","primaria","secundaria","preparatoria"),
                levels=c("primaria","secundaria","preparatoria","licenciatura",
                         "maestria","doctorado","posdoctorado"),
                ordered=TRUE)
(nivel_educativo_ordenado)
               
```

```{r}
nivel_educativo_ordenado <- factor (c(nivel_educativo_ordenado, nivel = nivel_educativo_ordenado, ordered = TRUE))
(nivel_educativo_ordenado)
```

```{r}
total_datos <- length(nivel_educativo_ordenado)
print(paste("Suma total de datos:", total_datos))
```

```{r}
frecuencia <- table(nivel_educativo_ordenado)
print("Frecuencia y orden de los datos:")
print(frecuencia)

```

```{r}
proporciones <- prop.table(frecuencia)
porcentajes <- round(proporciones * 100, 2)

tabla_resumen <- data.frame(
  Frecuencia = as.numeric(frecuencia),
  Proporciones = as.numeric(proporciones),
  Porcentajes = as.numeric(porcentajes)
)
rownames(tabla_resumen) <- names(frecuencia)
print("Tabla de Frecuencia, Proporciones y Porcentajes:")
print(tabla_resumen)
```

```{r}
frecuencia_minima <- min(frecuencia)
frecuencia_maxima <- max(frecuencia)
print(paste("Frecuencia mínima:", frecuencia_minima))
print(paste("Frecuencia máxima:", frecuencia_maxima))
```

```{r}
datos_numericos <- as.numeric(nivel_educativo_ordenado)
```

```{r}
resumen_datos <- summary(datos_numericos)
print("Resumen estadístico de los datos (cuartiles, mediana, etc.):")
print(resumen_datos)
```

```{r}
barplot(frecuencia,
        main = "Frecuencia de Nivel Educativo",
        xlab = "Nivel Educativo",
        ylab = "Frecuencia",
        col = rainbow(length(frecuencia)),
        las = 2) # las = 2 rota las etiquetas para que sean legibles
```




```{r}
pie(frecuencia,
    labels = paste(names(frecuencia), " (", porcentajes, "%)", sep = ""),
    main = "Proporción de Nivel Educativo",
    col = rainbow(length(frecuencia)))
```


```{r}
```


