---
title: "Examen"
author: "Aguirre Alvarado Danna Paola"
output: html_document
date: "2025-09-19"
---

```{r}
Examen <- c("Reprobado", "Aprobado", "Aprobado", "Aprobado", "Aprobado", "Reprobado", "Aprobado", "Reprobado", "Reprobado", "Aprobado", "Reprobado", "Reprobado", "Reprobado", "Reprobado", "Aprobado", "Reprobado", "Reprobado", "Aprobado", "Aprobado", "Reprobado", "Aprobado", "Aprobado", "Aprobado", "Aprobado", "Reprobado", "Aprobado", "Reprobado", "Aprobado", "Reprobado", "Reprobado", "Aprobado", "Reprobado", "Aprobado", "Reprobado", "Aprobado", "Reprobado", "Reprobado", "Aprobado", "Reprobado", "Reprobado", "Reprobado", "Aprobado", "Aprobado", "Aprobado", "Aprobado", "Reprobado", "Reprobado", "Reprobado", "Aprobado", "Reprobado")

Examen_F <- factor(Examen, levels = c("Reprobado", "Aprobado"))
```

```{r}
frecuencia_examen <- table(Examen_F)
print("Frecuencia de resultados de examen:")
print(frecuencia_examen)
```

```{r}
proporciones_examen <- prop.table(frecuencia_examen)
print("Proporciones de resultados de examen:")
print(proporciones_examen)
```

```{r}
max_freq_examen <- max(frecuencia_examen)
min_freq_examen <- min(frecuencia_examen)
print(paste("Frecuencia máxima:", max_freq_examen))
print(paste("Frecuencia mínima:", min_freq_examen))

```

```{r}
barplot(frecuencia_examen, 
        main = "Frecuencia de Resultados de Examen",
        xlab = "Resultado",
        ylab = "Frecuencia",
        col = c("red", "green"))
```

```{r}
porcentajes_examen <- round(proporciones_examen * 100, 1)
pie(frecuencia_examen, 
    labels = paste(names(frecuencia_examen), " (", porcentajes_examen, "%)", sep=""),
    main = "Proporción de Resultados de Examen",
    col = c("red", "green"))
```

