---
title: "Grado de Dolor"
author: "Aguirre Alvarado Danna Paola"
output: html_document
date: "2025-09-19"
---

```{r}
 Grado_de_dolor <- factor(c( "severo", "leve", "leve", "severo", "leve", "leve", "leve", "moderado", "moderado", "moderado", "moderado", "severo", "severo" , "moderado", "leve", "severo", "leve", "severo", "severo","severo", "leve", "moderado","severo", "severo","leve","leve","leve","severo","severo","leve"))

```

```{r}
Grado_de_dolor <- factor (c (Grado_de_dolor, levels = Grado_de_dolor, ordered = TRUE))
```

```{r}
suma_total_datos <- length(Grado_de_dolor)
print(paste("Suma total de datos:", suma_total_datos))
```

```{r}
frecuencia <- table(Grado_de_dolor)
print("Frecuencia absoluta:")
print(frecuencia)

```

```{r}
proporciones <- prop.table(frecuencia)
print("Proporciones:")
print(proporciones)
```

```{r}
frecuencia_maxima <- max(frecuencia)
frecuencia_minima <- min(frecuencia)
print(paste("Frecuencia máxima:", frecuencia_maxima))
print(paste("Frecuencia mínima:", frecuencia_minima))
```

```{r}
barplot(frecuencia,
        main = "Frecuencia del Grado de Dolor",
        xlab = "Grado de Dolor",
        ylab = "Frecuencia",
        col = c("green", "orange", "red"),
        names.arg = names(frecuencia))
```

```{r}
porcentajes <- round(proporciones * 100, 1)
```

```{r}
pie(frecuencia,
    labels = paste(names(frecuencia), " (", porcentajes, "%)", sep = ""),
    main = "Proporción del Grado de Dolor",
    col = c("green", "orange", "red"))
```
