---
title: "MARCA DE CELULAR"
author: "Aguirre Alvarado Danna Paola"
output: html_document
date: "2025-09-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
Marca_celular <- c("Apple", "Samsung", "LG", "Huawei", "OnePlus", "Sony", "Apple", "Samsung",
 "Huawei", "Huawei", "Nokia", "OnePlus", "Motorola", "Xiaomi", "Samsung", "Apple", "Apple", "Motorola",
 "Samsung", "Samsung", "Huawei", "Motorola", "Nokia", "OnePlus", "Huawei", "Huawei",
 "Apple", "LG", "Apple", "Xiaomi", "LG", "OnePlus", "OnePlus", "LG", "Sony", "Samsung", "Apple",
 "Xiaomi", "Oppo", "Motorola", "LG", "Samsung", "Motorola", "Samsung", "Nokia", "OnePlus", "OnePlus",
 "Oppo", "Sony", "Nokia", "Huawei", "LG", "Sony", "Xiaomi", "LG", "Huawei", "LG", "Nokia",
 "Xiaomi", "Sony", "OnePlus", "LG", "Xiaomi", "OnePlus", "Oppo", "Nokia", "Huawei", "Xiaomi", "Oppo", "Oppo")
(Marca_celular)
```

```{r}
summary(Marca_celular)
```

```{r}
Marca_ord <- sort(Marca_celular); (Marca_ord)
```

```{r}
freq <- table(Marca_celular)
porc <- round(prop.table(freq)*100, 1)
mi_min <- names(freq)[which.min(freq)] 
(mi_min)
mi_max <- names(freq)[which.max(freq)] 
(mi_max)
```

```{r}
barplot(Frecuencia_ordenada,
        main = "Frecuencia de Marcas de Celulares",
        xlab = "Marca de Celular",
        ylab = "Frecuencia",
        col = rainbow(length(Frecuencia_ordenada)),
        las = 2) 
```

```{r}
pie(freq,
    labels = paste(names(freq), porc, "%"),
    col = rainbow(length(freq), 0.8),
    main = "Marcas de Celulares")

```

```{r}

```