---
title: "Tipo de sangre"
author: "Aguirre Alavardo Danna Paola"
output: html_document
date: "2025-09-14"
---

```{r}
tipo_de_sangre <- c("A-", "AB-", "AB+", "B+", "O-", "O+", "B+", "A-", "O-", "B-", "A-", "A-", "O+", "A+",
 "O+", "AB+", "B+", "AB+", "AB-", "B-", "O-", "O+", "B+", "O+", "O+", "O+", "A+", "O-", "AB-", "A-", "B+",
 "O-", "B-", "A-", "A-", "AB-", "B+", "AB-", "A-", "B+", "A-", "AB-", "O-", "AB+", "B+", "O+", "B-", "O-", "A-",
 "AB-", "O+", "AB+", "AB+", "B+", "O-", "AB+", "AB+", "AB-", "A-", "O-", "AB+", "AB+", "A+", "A+",
 "O+", "B+", "AB-", "O-", "A-", "A+", "A+", "B-", "B-", "B-", "A+", "A-", "AB-", "A-", "A-", "AB+")
               
```

```{r}
frecuencia_sangre <- table(tipo_de_sangre)
print("Frecuencia absoluta del tipo de sangre:")
print(frecuencia_sangre)
```

```{r}
proporciones_sangre <- prop.table(frecuencia_sangre)
print("Proporciones del tipo de sangre:")
print(proporciones_sangre)
```

```{r}
frecuencia_maxima_sangre <- max(frecuencia_sangre)
frecuencia_minima_sangre <- min(frecuencia_sangre)
print(paste("Frecuencia máxima:", frecuencia_maxima_sangre))
print(paste("Frecuencia mínima:", frecuencia_minima_sangre))
```

```{r}
barplot(frecuencia_sangre,
        main = "Frecuencia de Tipos de Sangre",
        xlab = "Tipo de Sangre",
        ylab = "Frecuencia",
        col = rainbow(length(frecuencia_sangre)))
```

```{r}
porcentajes_sangre <- round(proporciones_sangre * 100, 1)
pie(frecuencia_sangre,
    labels = paste(names(frecuencia_sangre), " (", porcentajes_sangre, "%)", sep = ""),
    main = "Proporción de Tipos de Sangre",
    col = rainbow(length(frecuencia_sangre)))
legend("topright",
       legend = names(frecuencia_sangre),
       fill = rainbow(length(frecuencia_sangre)))
```



